vscode:
  extensions:
    - vscjava.vscode-java-test@0.22.0:BlvjRRJyZszeJzIS+xEHIA==
    - vscjava.vscode-java-debug@0.24.0:4bjzZag4ZW2bFcv6qiRCEg==
    - vscjava.vscode-java-dependency@0.6.0:XkyeyJWk/nK6xEO886ltYg==
    - richardwillis.vscode-gradle@2.4.1:GclbsaS8Uhl3MfnUNLkICA==